### ISSUE TITLE
Double Pendulum su Scratch

### ISSUE THREAD

**Issue by sfederici** [Mittagskogel/Sulfurous#100]
The pendulum leaves a white trace, instead of a red trace like in the original project.

https://scratch.mit.edu/projects/20528746/
https://sulfurous.aau.at/#20528746
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by htmlgames** [comment]
Couldn't resist!

when I start as clone block sets brightness to 200 (this is the same as setting it to 0)

if you remix the project with 0 it works.

so brightness % 200 should be the fix.

**Comment by sfederici** [comment]
Ok! By setting brightness to 0 the trace color is brownish instead of red. So, is there a difference in the way Scratch and Sulfurous handle brightness values?

**Comment by htmlgames** [comment]
that could be the color effect (ie change it from 80 to something else) - it's very subtle though on my (old) monitor, could even be how RGB is being handled internally.

**Comment by FRALEXAlexander** [comment]
The brightness is fixed but the color is still brownish i will try to fix also the color soon

**Comment by FRALEXAlexander** [comment]
The color is now red and with the brightness also fixed I think this issue can be closed.
