### ISSUE TITLE
into the wind su Scratch

### ISSUE THREAD

**Issue by sfederici** [Mittagskogel/Sulfurous#101]
The flower jumps up and down instead of oscillating.

https://scratch.mit.edu/projects/215175901/
https://sulfurous.aau.at/#215175901
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by htmlgames** [comment]
SVG centering issue.

If you manually (re)center the flower image it works.

**Comment by sfederici** [comment]
Thanks. But why the project works in Scratch and doesn't work instead in Sulfurous?

**Comment by htmlgames** [comment]
Looks like Scratch re-centers images for certain (edge?) cases - you would need to examine the raw svg data in this case and work back from there.

One of the svg images is ok (2nd one I think) so at least you can start by comparing the 1st svg raw data with this one. Look for offset values within the svg attributes - maybe scratch ignores them?

**Comment by FRALEXAlexander** [comment]
The way sulfurous executes the Project is the right one Scratch 2.0 has a bug here this is already fixed in Scratch 3.0
