### ISSUE TITLE
Gem Collector auf Scratch

### ISSUE THREAD

**Issue by demesos** [Mittagskogel/Sulfurous#103]
Sounds are not playing under Chrome. They work with Firefox though.

https://scratch.mit.edu/projects/220250499/
https://sulfurous.aau.at/#220250499
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

**Comment by FRALEXAlexander** [comment]
In version V67 of Chrome is the sound working
