### ISSUE TITLE
Can't Get Lists

### ISSUE THREAD

**Issue by Robstruck15** [Mittagskogel/Sulfurous#107]
When I tried to put in a projects that the whole game needs lists to use it doesn't load the lists. Can you fix this?
![no-lists](https://user-images.githubusercontent.com/28578898/40881236-c1f01118-667e-11e8-88c5-7c0cef34f4b6.png)

**Comment by Robstruck15** [comment]
The project btw is https://scratch.mit.edu/projects/227084362/

**Comment by FRALEXAlexander** [comment]
Lists will work in version 0.94
