### ISSUE TITLE
3D Faroes Eclipse Experience

### ISSUE THREAD

**Issue by sfederici** [Mittagskogel/Sulfurous#11]
A bit faster in Scratch. In Phosphorous the objects leave "traces" when moving.

http://scratch.mit.edu/projects/25071751/
http://mittagskogel.github.io/#25071751
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36

**Comment by FRALEXGAMING** [comment]
Sulfurous is now much faster than Scratch in this project and i can not see "traces".

**Comment by sfederici** [comment]
Confirm. Sulfurous now is MUCH faster  and there are no traces at all :-) Thanks.
