### ISSUE TITLE
i dont know why

### ISSUE THREAD

**Issue by h31p6e** [Mittagskogel/Sulfurous#113]
https://scratch.mit.edu/projects/17088932
https://newton.nes.aau.at/~sulfurous/#17088932

```
Error: XHR Error
    at XMLHttpRequest.xhr.onerror (http://www.mckaulay.com/monorail/js/phosphorus.js:252:21)
```

**Comment by FRALEXAlexander** [comment]
I did not see this error durring my testing please reopen the issue if you still get the error and explain the error better.
