### ISSUE TITLE
Animal Kingdom  (Very Slow)

### ISSUE THREAD

**Issue by LiamBogur** [Mittagskogel/Sulfurous#114]
https://scratch.mit.edu/projects/230579832/
https://sulfurous.aau.at/#230579832
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
My Game Is Very Slow! Can you try optimising it or making a exe compiler?

**Comment by FRALEXAlexander** [comment]
Your game runs without lags or problems as far as i can tell reopen the issue and explain the problem better.
