### ISSUE TITLE
https://scratch.mit.edu/projects/230047282/

### ISSUE THREAD

**Issue by MathemagicalCalibrations** [Mittagskogel/Sulfurous#115]
https://scratch.mit.edu/projects/230047282/
https://sulfurous.aau.at/#230047282
Mozilla/5.0 (Linux; Android 8.0.0; moto g(6) plus Build/OPW27.113-45) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

SVG sprite shown as black square.

**Comment by FRALEXAlexander** [comment]
Please publish your project on scratch so that i can view your code as a help in bug fixing

**Comment by FRALEXAlexander** [comment]
I dont see a black Square I see the dinosour reopen the issue if you still have the error

**Comment by FRALEXAlexander** [comment]
Thanks for that Information.
