### ISSUE TITLE
So... Where's the lists?

### ISSUE THREAD

**Issue by MikeDev101** [Mittagskogel/Sulfurous#116]
Well for some odd reason In my Kernel project "NX Kernel" I tried to make it compatible with this player but lists wouldn't show on-screen and data wouldn't save, as my kernel would keep on giving me a "List I/O Error." Now, I have it written in the project's description: "Not recommended for Phosphorus or Sulfurous player(s)".

Please fix this, as I would like to make it compatible with this player, and the Phosphorus player... 

(I was going to add my project here, but it seems like it doesn't like the player...)
https://sulfurous.aau.at/
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by FRALEXAlexander** [comment]
Lists will work in version 0.94
