### ISSUE TITLE
Adding Support for the 16:9 Scratch Mod

### ISSUE THREAD

**Issue by callowaysutton** [Mittagskogel/Sulfurous#12]
Hi I found a scratch modification (for 2.0) that supports 16:9 aspect ratio and resolution.
I'm not sure if it is already, but could you support this mod somehow?

**Comment by FRALEXGAMING** [comment]
Please Post a Link to the mod.

**Comment by callowaysutton** [comment]
https://scratch.mit.edu/discuss/topic/183243/?page=1#post-1789581

**Comment by callowaysutton** [comment]
https://drive.google.com/file/d/0B8VD2SJxIyv-V3JPZVhiYm1zdlE/view?usp=sharing
This is his source code

**Comment by FRALEXGAMING** [comment]
Thanks I will put this on our TODO list.

**Comment by Mittagskogel** [comment]
Arbitrary aspect ratio support has been added for package and embed.

**Comment by callowaysutton** [comment]
woot woot
