### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by jay79984858** [Mittagskogel/Sulfurous#120]
https://scratch.mit.edu/projects/27676406
https://newton.nes.aau.at/~sulfurous/#27676406

```
onload@https://sulfurous.aau.at/js/phosphorus.js:463:32
```

**Comment by htmlgames** [comment]
see issue https://github.com/Mittagskogel/Sulfurous/issues/122 for fix

**Comment by FRALEXAlexander** [comment]
see #122
