### ISSUE TITLE
...

### ISSUE THREAD

**Issue by Minecrafter615** [Mittagskogel/Sulfurous#122]
https://scratch.mit.edu/projects/151360789
https://newton.nes.aau.at/~sulfurous/#151360789

```
Error: HTTP 404: Not Found
    at XMLHttpRequest.xhr.onload (https://sulfurous.aau.at/js/phosphorus.js:463:23)
```

**Comment by htmlgames** [comment]
You need this fix:

https://github.com/htmlgames/htmlgames.github.io/blob/5dba25858b8fa4b040d9fc715e15216fa860a585/htmlgames/differences/UAT/itchy/phosphorus.js#L4238

**Comment by FRALEXAlexander** [comment]
There was an issue with the URL for the soundbank of sulfurous now it should work.
