### ISSUE TITLE
Packaging bug

### ISSUE THREAD

**Issue by ThreadSnake** [Mittagskogel/Sulfurous#123]
Packaging projects comes up with a bug every time.
I don't have any clue what's causing this.
![sb](https://user-images.githubusercontent.com/34461450/42717583-0e034806-86d0-11e8-9944-1ca2daea3026.png)

```
Error: HTTP 404: Not Found
    at XMLHttpRequest.xhr.onload (https://sulfurous.aau.at/js/phosphorus.js:463:23)
```

**Comment by htmlgames** [comment]
Please see issue https://github.com/Mittagskogel/Sulfurous/issues/119

**Comment by FRALEXAlexander** [comment]
see #122
