### ISSUE TITLE
Just One Button auf Scratch

### ISSUE THREAD

**Issue by demesos** [Mittagskogel/Sulfurous#125]
The packaged game does not start.

I packaged as https://sulfurous.aau.at/html/app.html?id=237031623&turbo=false&full-screen=false&aspect-x=&aspect-y=&resolution-x=480&resolution-y=360

https://scratch.mit.edu/projects/237031623/
https://sulfurous.aau.at/#237031623
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0

**Comment by FRALEXAlexander** [comment]
We fixed the package problem
