### ISSUE TITLE
Sulfurous seems completely borked

### ISSUE THREAD

**Issue by TiberiumFusion** [Mittagskogel/Sulfurous#126]
No matter what project I try to run, no matter what browser I use, and no matter how long I wait, the Sulfurous player appears to do absolutely nothing when told to run a project.

Everything was working just fine before the recent-ish commits. I'd wager that some untested changes from the multitude of commits on July 23 are to blame.

The most recent date I can confirm that Sulfurous was working was earlier this month, on July 5. I do not know if that was before or after the several commits that were made that day.

This is what the player site looks like when trying to run a project: https://s22.postimg.cc/kpgrnj5cx/bad_sulfurous.png
The blue progress bar behind the URL field does not appear. There is no visual activity on the page whatsoever.

To clarify:
- Direct links (such as https://sulfurous.aau.at/#230593234) do not work
- Pasting links into the URL field on the site does not work
- Clicking any of the player buttons (green flag, stop, fullscreen, pause) does not do anything
- Phosphorus still works just fine, so I highly doubt this is an issue caused by a change by the Scratch Team

**Comment by TiberiumFusion** [comment]
Yes, I did wipe my entire browser cache (Firefox ESR 52.9.0), both using the browser's inline cleaner and CCleaner. I also tried with a completely fresh install of IE11, which I know I've never visited the Sulfurous site before with.

**Comment by TiberiumFusion** [comment]
I just tested with Chromium on the same two devices and found Sulfurous to function normally. I don't want to jump to any conclusions, but it seems as if you've taken Sulfurous in a direction that alienates non-google systems?

To clarify: Sulfurous does not function at all in FF esr or IE, but works fine with Chromium.

**Comment by FRALEXAlexander** [comment]
We could unfortunately not replicate your issue. I will close that one. If you still have this problem reopen the issue and post the output of the console in the browser.

**Comment by TiberiumFusion** [comment]
The issue still exists as of today.
Specifically:
- This still occurs in both Firefox ESR 52.9.0 and IE 11
- This issue began occurring after the July 23, 2018 commits
- The sulfurous player does not load anything. Pasting a project ID/url into the input field does nothing. Using a sulfurous url with a #projectid does nothing. Basically, nothing on the page changes in reaction to entering a project ID.
- I checked some other browsers just now. The issue does _not_ occur in Chromium 83 or Palemoon 28.10.0 (modern FF esr derivative)

Also worth noting is that Phosphorus still works just fine in both FF 52 esr and IE 11.

Console output from FF 52.9.0:
![sulfurous console ff esr](https://user-images.githubusercontent.com/6332277/85978518-e3779580-b9ac-11ea-9dd3-7fd46be71cf0.png)

It seems like sulfurous uses some newer javascript syntax that is foreign to 2+ year old browsers. On a sidenote, when this issue first appeared 2 years ago, FF 52.9.0 esr was less than a month old. The July 23 2018 commits must have included what would have been bleeding edge javascript at the time.

**Comment by FRALEXAlexander** [comment]
I am sorry to hear this. We have a problem in supporting older browser versions our time and manpower is very limited. Please consider using Chrome or a newer version of Firefox. The version 77.0.1 (64-Bit) works fine for me. If we have time we will look into your problem.

**Comment by TiberiumFusion** [comment]
@FRALEXAlexander Thanks, I absolutely understand. It's a pretty minor issue now that Chromium and other modern browsers are no longer affected (as opposed to 2 years ago when I reported this, when sulfurous was broken in every single browser I tested). The availability of unaffected browsers is decent and I'm sure you guys have much more important things to focus on.
