### ISSUE TITLE
kiharusi-v0-4-2b freeze

### ISSUE THREAD

**Issue by diamondMartin** [Mittagskogel/Sulfurous#130]
Complete freeze and mess during the second level.
Sprites render worse than in Phosphorous? Ugly shadow and other png color problems.

Hmmm. sometimes not crashing (Chrome)?

https://scratch.mit.edu/projects/239376294/
https://sulfurous.aau.at/#239376294
Mozilla/5.0 (Windows NT 6.3; WOW64; rv:61.0) Gecko/20100101 Firefox/61.0
Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/42478729/44287123-473ebc80-a274-11e8-85fb-831680282442.png)

**Comment by diamondMartin** [comment]
Skip forward button makes the problem now! Trying to clean things.

**Comment by FRALEXAlexander** [comment]
The project is not on scratch anymore so I cant investigate the problem. Open a new issue if you reupload the project.
