### ISSUE TITLE
3D Engine (v1.3) su Scratch

### ISSUE THREAD

**Issue by sfederici** [Mittagskogel/Sulfurous#137]
Blank Stage

https://scratch.mit.edu/projects/235786326/
https://sulfurous.aau.at/#235786326
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by sfederici** [comment]
Note: it works in Phosphorus

**Comment by FRALEXAlexander** [comment]
I tested it and it worked could you test it again and see if you still get a blank stage ?

**Comment by sfederici** [comment]
No. Now it works. Thanks.
