### ISSUE TITLE
The Cookie Minute auf Scratch

### ISSUE THREAD

**Issue by demesos** [Mittagskogel/Sulfurous#138]
On Android, the gameplay is choppy and the variables are flickering on and off.

https://scratch.mit.edu/projects/247908845/
https://sulfurous.aau.at/#247908845
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

**Comment by FRALEXAlexander** [comment]
On my Andriod device (Samsung S10+) it works fine. Plese reopen the issue if you still have this issue
