### ISSUE TITLE
3D Platform Speedrun auf Scratch

### ISSUE THREAD

**Issue by demesos** [Mittagskogel/Sulfurous#139]
Project does not display anything at start, you can only hear the music. Seems like it hangs itself in the starting phase, probably because of the cloud access?

https://scratch.mit.edu/projects/14305883/
https://sulfurous.aau.at/#14305883
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by FRALEXAlexander** [comment]
In my test it works fine but without the cloud variable as expected
