### ISSUE TITLE
Gomoku - Five in a Row auf Scratch (invisible sprite problem)

### ISSUE THREAD

**Issue by demesos** [Mittagskogel/Sulfurous#14]
The placed stones are not visible. The game works though, it gives feedback when you lose or win.

http://scratch.mit.edu/projects/103822876/
http://mittagskogel.github.io/#103822876
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by FRALEXGAMING** [comment]
Now working in Sulfurous. Since Version 0.81
