### ISSUE TITLE
My project needs you to click to control the player but Sulforous can't do that!

### ISSUE THREAD

**Issue by michaelg130** [Mittagskogel/Sulfurous#140]
https://scratch.mit.edu/projects/247834273/
https://sulfurous.aau.at/#247834273
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by FRALEXAlexander** [comment]
This projects does the same as on the scratch site.
