### ISSUE TITLE
NPR Low Poly with Delaunay Triangulation

### ISSUE THREAD

**Issue by gtoal** [Mittagskogel/Sulfurous#142]
This must have worked for the author but it doesn't seem to work for me.

https://scratch.mit.edu/projects/246475360
https://newton.nes.aau.at/~sulfurous/#246475360

```
Error: XHR Error
    at XMLHttpRequest.xhr.onerror (https://sulfurous.aau.at/js/phosphorus.js:473:20)
```

**Comment by FRALEXAlexander** [comment]
I unfortunatelly cant reproduce the problem please try to load the project again and reopen the issue if the problem still occurres.
