### ISSUE TITLE
Greenhouse Gases Simulator su Scratch

### ISSUE THREAD

**Issue by sfederici** [Mittagskogel/Sulfurous#144]
Blank Stage

https://scratch.mit.edu/projects/210686453/
https://sulfurous.aau.at/#210686453
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by FRALEXAlexander** [comment]
It's working just fine for me. Reopen the issue and post the output of the browser console if you still have the issue.

**Comment by sfederici** [comment]
It works fine for me too now
