### ISSUE TITLE
Five Nights at Alzter'z 2 Demo

### ISSUE THREAD

**Issue by Alzter** [Mittagskogel/Sulfurous#15]
On Sulfurous, My game is very glitchy, most object faces are gone, the fonts are gone and most gradients are gone.

https://scratch.mit.edu/projects/139838344/
http://mittagskogel.github.io/#139838344
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by FRALEXAlexander** [comment]
Your project works just fine in Sulfurous now.
