### ISSUE TITLE
https://scratch.mit.edu/projects/254511243/

### ISSUE THREAD

**Issue by CANSLP** [Mittagskogel/Sulfurous#152]
hey, I'm stamping with a black-transparent gradient to do a flashlight effect and the black is like?? erasing?? like wherever it should be black it's making whatever's being stamped more transparent based on it's opacity??? is the way you're storing pen color data just setting a transparency value independently or like why would this happen?

https://scratch.mit.edu/projects/254511243/
https://sulfurous.aau.at/#254511243
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by FRALEXAlexander** [comment]
It seems to work the same on sulfurous and scratch. Reopen the issue if you still have the problem and add screenshots.
