### ISSUE TITLE
https://scratch.mit.edu/projects/22757740/

### ISSUE THREAD

**Issue by 3RAW** [Mittagskogel/Sulfurous#155]
https://scratch.mit.edu/projects/22757740/
https://sulfurous.aau.at/#22757740
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

**Comment by 3RAW** [comment]
Not all pen works

**Comment by FRALEXAlexander** [comment]
I cant check the project on scratch if you reupload it and the error still occurs please open a new issue.
