### ISSUE TITLE
https://scratch.mit.edu/projects/261866249/

### ISSUE THREAD

**Issue by Scratch13764** [Mittagskogel/Sulfurous#159]
Hi, I'm using chrome for sulfurous (I've tried Opera and it's a little better). I think this project is really unreasonably laggy, and it gets worse framerates then it does in scratch. I don't know what's tripping it up but I would assume it has something to do with the high amount of list processing. I'll be sharing the project very soon so you can see the actual project, for now here's the sb2. Another thing that's not great is that on the title screen the colors are off. See https://phosphorus.github.io/#261866249 to see what it's supposed to look like until I can share it. Thanks :)
Here's the link to the sb2 so you can look at it:
https://drive.google.com/file/d/104aUOkqaU8snKzmRU_og4hQSJigYbqi-/view?usp=sharing

https://scratch.mit.edu/projects/261866249/
https://sulfurous.aau.at/#261866249
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36

**Comment by FRALEXAlexander** [comment]
It does not seem to be laggy
