### ISSUE TITLE
NSMB Engine

### ISSUE THREAD

**Issue by Alzter** [Mittagskogel/Sulfurous#16]
Various Sounds sound extremely low quality, and fuzzy.

http://scratch.mit.edu/projects/139238097/
http://mittagskogel.github.io/#139238097
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by Mittagskogel** [comment]
Fixed.
