### ISSUE TITLE
School Bells v3.12

### ISSUE THREAD

**Issue by ebarrows** [Mittagskogel/Sulfurous#161]
Arrays not visible.

https://scratch.mit.edu/projects/267926447/
https://sulfurous.aau.at/#267926447
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

**Comment by FRALEXAlexander** [comment]
The array are visible.
