### ISSUE TITLE
Sulfurous now useless and unusable because of Scratch 3.0

### ISSUE THREAD

**Issue by Eribetra** [Mittagskogel/Sulfurous#162]
Because Scratch 3.0, based off HTML5, just launched, Sulfurous now cannot load .sb3 projects, and as such, is useless and unusable.

**Comment by JerryCjr** [comment]
EXM, i want to ask when the player can support scratch3.0?

**Comment by JerryCjr** [comment]
@demesos

**Comment by demesos** [comment]
> 
> 
> EXM, i want to ask when the player can support scratch3.0?

We will work on it in July 2019.

**Comment by JerryCjr** [comment]
ok thank u!
