### ISSUE TITLE
https://scratch.mit.edu/projects/281144739/

### ISSUE THREAD

**Issue by capitjeff21** [Mittagskogel/Sulfurous#167]
https://scratch.mit.edu/projects/281144739/
https://sulfurous.aau.at/#281144739
Mozilla/5.0 (X11; CrOS x86_64 10895.78.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.120 Safari/537.36

So does Sulfurous not work with Scratch 3? Cause I have a game with a bunch of players as well that has now been down for almost 3 weeks.

**Comment by demesos** [comment]
Sulfurous does not (yet) work with Scratch 3.0. We are planning to add this feature within the next half year. To publish something, you can meanwhile make your game with the Scratch 2.0 offline editor and upload it with the build-in upload function, the project then is still a 2.0 project and will work with Sulfurous. In any case looking forward to have your game working with Sulfurous soon!

**Comment by FRALEXAlexander** [comment]
The project loads now but I cant check the expected behavior because the project is no longer on scratch.
