### ISSUE TITLE
https://scratch.mit.edu/projects/282456745/

### ISSUE THREAD

**Issue by 03172008** [Mittagskogel/Sulfurous#168]
https://scratch.mit.edu/projects/282456745/
https://sulfurous.aau.at/#282456745
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by FRALEXAlexander** [comment]
The Project works now
