### ISSUE TITLE
Issue with loading games

### ISSUE THREAD

**Issue by zman6906** [Mittagskogel/Sulfurous#169]
I can't open anything bigger than a very small mini-game in sulfurous. Every time, it just gets stuck in the middle of loading and will never come out of its position. It keeps going backwards to the same position... right in between the "t" and the "s" in the url. Even when trying to restart my computer several times, reconnecting to the WiFi, even when I have a strong signal, it still won't load. I am using an HP Chromebook 11 G5 with 4 GB of RAM, and it has worked before, but it won't work anymore even with the newest version of my system software.

**Comment by FRALEXAlexander** [comment]
please send me the project id off the project you tried

**Comment by zman6906** [comment]
Project id is 1274509

**Comment by FRALEXAlexander** [comment]
Thank you for the ID I checked it. The project is corrupted if you remix it it will work again. But not in the current version of sulfurous. The remix is a sb3 project witch is currently not implemented in the sulfurous player. We work on a version for sb3 projeccts

**Comment by zman6906** [comment]
Ok thank you :)

**Comment by FRALEXAlexander** [comment]
Problem is fixed issue will be closed ( not der SB3 Problem but the initial problem)
