### ISSUE TITLE
https://scratch.mit.edu/projects/267926447/

### ISSUE THREAD

**Issue by ebarrows** [Mittagskogel/Sulfurous#170]
Sulfurous is not reflecting updates in the scratch code.

https://scratch.mit.edu/projects/267926447/
https://sulfurous.aau.at/#267926447
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

**Comment by FRALEXAlexander** [comment]
The project is not available on scratch anymore so I cant check your problem
