### ISSUE TITLE
https://scratch.mit.edu/projects/292229893/

### ISSUE THREAD

**Issue by Gamereric21** [Mittagskogel/Sulfurous#175]
https://scratch.mit.edu/projects/292229893/
https://sulfurous.aau.at/#292229893
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36

Please make this work when I enter it! also...the original shows an old version, I updated it

**Comment by FRALEXAlexander** [comment]
I cant check your problem because the project is not on the scratch server anymore
