### ISSUE TITLE
https://scratch.mit.edu/projects/294171285/

### ISSUE THREAD

**Issue by qwik** [Mittagskogel/Sulfurous#179]
the project file never loads

https://scratch.mit.edu/projects/294171285/
https://sulfurous.aau.at/#294171285
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15

**Comment by FRALEXAlexander** [comment]
This project works now
