### ISSUE TITLE
SPACE INVADERS MILLORAT amb nau final en Scratch

### ISSUE THREAD

**Issue by eloiole** [Mittagskogel/Sulfurous#18]
Martians in the first and third rows, are changing between diferent index dresses and in the program they  change between the two correct dresses

http://scratch.mit.edu/projects/133475977/
http://mittagskogel.github.io/#133475977
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by FRALEXGAMING** [comment]
The project is now running fine on Sulfurous I think, becouse i can not check the original version on Scratch (maybe removed from you).
