### ISSUE TITLE
https://scratch.mit.edu/projects/288992686/

### ISSUE THREAD

**Issue by memememwhatamidoing** [Mittagskogel/Sulfurous#180]
PLEASE HELP I CAN BARELY PLAY MY PROJECT IN SCRATCH AND SULFUROUS WON'T PLAY IT EITHER. Thanks!
https://scratch.mit.edu/projects/288992686/
https://sulfurous.aau.at/#288992686
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

**Comment by metype** [comment]
If it was made in the new editor you'll have to wait until they upgrade this tool to read .sb3 files, as currently it cannot, and if no .sb2 file is associated with your project Sulfurous cannot read the project.

**Comment by FRALEXAlexander** [comment]
dublicate
