### ISSUE TITLE
Doesn't load project as if it doesn't exist.

### ISSUE THREAD

**Issue by TheRealMandMs05** [Mittagskogel/Sulfurous#184]
https://scratch.mit.edu/projects/300287475/
https://sulfurous.aau.at/#300287475
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

**Comment by Shrubhog** [comment]
Both Sulfurous and Phosphorus are outdated and not needed at this time. Scratch now has a CORS policy, which blocks scripts from reading the project, and is now 3.0. 3.0 is in HTML5 and JS which is what these compilers used to compile 2.0 projects to.

**Comment by demesos** [comment]
Sulfurous and Phosphorus still workswith projects that have been made in 2.0. Since Scratch 3.0 is not fully backwards compatible, so for some projects this is the only way to run these projects without Flash.

**Comment by Shrubhog** [comment]
Cool. I haven't seen any projects that do what you describe, but I'm sure they exist.

**Comment by FRALEXAlexander** [comment]
It loads now
