### ISSUE TITLE
https://scratch.mit.edu/projects/300000123/

### ISSUE THREAD

**Issue by Ezequiel052** [Mittagskogel/Sulfurous#188]
https://scratch.mit.edu/projects/300000123/
https://sulfurous.aau.at/#300000123
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

actually both sulfurous and phosphorus dont work in scratch 3.0, what is making them useless

**Comment by demesos** [comment]
we are working on the issue with Scratch 3 made projects. So far the use of Sulfuruous is to play Scratch 2.0 projects which don't work in Scratch 3.0

**Comment by FRALEXAlexander** [comment]
This project loads now.
