### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by jfcogr** [Mittagskogel/Sulfurous#189]
I can't load my project for doing an .apk, what's happend? thanks

https://scratch.mit.edu/projects/307777434
https://newton.nes.aau.at/~sulfurous/#307777434

```
IO.load/xhr.onload@https://sulfurous.aau.at/js/phosphorus.js:469:23

```

**Comment by FRALEXAlexander** [comment]
The project is not on the scratch servers that means sulfurous cant load the project
