### ISSUE TITLE
Meta NES Emulator su Scratch

### ISSUE THREAD

**Issue by sfederici** [Mittagskogel/Sulfurous#19]
Nothing happens.

http://scratch.mit.edu/projects/141205192/
http://newton.nes.aau.at/~sulfurous/#141205192
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by FRALEXGAMING** [comment]
With the new Version 0.81 of Sulfurous i get the same Result as on Scratch.

**Comment by sfederici** [comment]
Is the new version the one I see online? Online I'm still getting a blank Stage (https://sulfurous.aau.at/~sulfurous/#141205192)
