### ISSUE TITLE
https://scratch.mit.edu/projects/307777434/

### ISSUE THREAD

**Issue by jfcogr** [Mittagskogel/Sulfurous#190]
Hi, i can't load my project, whats's happend?

https://scratch.mit.edu/projects/307777434/
https://sulfurous.aau.at/#307777434
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by demesos** [comment]
If your project was done with Scratch 3.0, it cannot be played with Sulfurous at the moment, but we are working on the issue.

**Comment by FRALEXAlexander** [comment]
This project loads now.
