### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Jurn1304** [Mittagskogel/Sulfurous#192]
https://scratch.mit.edu/projects/292990357
https://newton.nes.aau.at/~sulfurous/#292990357

```
Error: HTTP 404: 
    at XMLHttpRequest.xhr.onload (https://sulfurous.aau.at/js/phosphorus.js:469:23)
```

**Comment by FRALEXAlexander** [comment]
This project does not exist on the scratch server so sulfurous cant load it
