### ISSUE TITLE
"You can also drag a local .sb2 project onto this page."

### ISSUE THREAD

**Issue by PiotrGrochowski** [Mittagskogel/Sulfurous#194]
That doesn't appear to be functional!

**Comment by FRALEXAlexander** [comment]
I tested it and it worked without a problem if you still have this problem reopen the issue and add your system informations and the project you tested

**Comment by PiotrGrochowski** [comment]
Project I used: https://tetrisreturn.netlify.com/tetris2019.sb2

Firefox ESR 52.4.1 (32-bit). Using "drag-and-drop" to a sb2 file on this page gives me the file back in a download prompt:

https://i.imgur.com/vsrn7Bu.png

When I accept to open with "sb2_auto_file", the file opens in the offline Scratch 2.0 editor on my PC.

**Comment by PiotrGrochowski** [comment]
And my operating system is Windows 10 from the popular OS series named Microsoft Windows. **I request a reopen.**

**Comment by PiotrGrochowski** [comment]
The file I shared has a peculiar property of failing to load in Scratch 3.0. However, this is irrelevant to the issue; this seems to happen with *any sb2 file*.

**Comment by PiotrGrochowski** [comment]
by "this seems to happen with any sb2 file." I don't mean the Scratch 3.0 bug I mean this issue

**Comment by FRALEXAlexander** [comment]
Try to drag it over the url in the middle of the screen

**Comment by FRALEXAlexander** [comment]
Your particular project seams not to work but others do maybe the save file is currapted. The project json seams a bit odd for example in the lists are some elements with brackets and some without maybe that is part of the problem you discribed with scratch 3.

**Comment by PiotrGrochowski** [comment]
"The project json seams a bit odd for example in the lists are some elements with brackets and some without" What do you mean? The json is the same as that exported by Scratch 2.0, except that I replaced the sounds list in Stage with my own modified code so that the original sounds work correctly.

You tested the project and it didn't work? Note that I JSONhacked this project for the sounds not to be compressed. There are 16-bit PCM sounds as well as 8-bit PCM sounds. Does this support 8-bit PCM?

The thing is, this issue happens regardless of the sb2 file I use.

When I "drag it over the url in the middle of the screen" I get this: https://i.imgur.com/pgpPPLp.png but with the mouse cursor in the middle as well. When I release the mouse button, the file is dropped but nothing happens at all. Have you tested for the particular Firefox version I used?

**Comment by FRALEXAlexander** [comment]
I cant see the url or anything in your picture that is not helpfull at all it is possible that the problem has todo with your version just update to the newest version. Your JSON hack could have currapted it when you saved it maybe the charset has changed or some other formating error happend

**Comment by PiotrGrochowski** [comment]
The sb2 itself has nothing to do with this. The issue itself happens with any sb2 file.

**Also, I refuse to upgrade Firefox.**

**Comment by demesos** [comment]
I opened your tetris2019.sb2 with the Scratch 2 offline editor and saved it again. Now it seems to work - at least it starts when you drag it into sulfurous. The refurbished file is here: https://sulfurous.aau.at/~wilfried/tetris2019_2.sb2 Piotr, can you check if it works as intented?

**Comment by PiotrGrochowski** [comment]
"I opened your tetris2019.sb2 with the Scratch 2 offline editor and saved it again."

This makes the sounds compressed. The original file didn't have compressed sounds. Playtest both the original and the Scratch-saved file in Scratch 2.0 and you might hear the difference in sound, for example in the pause sound (pause is by default assigned to enter).

**Also, I said any sb2 file has this issue. It doesn't matter, I can't test any sb2 file because all of them have this issue.**

**Comment by PiotrGrochowski** [comment]
Note that this game allows keyboard control configuration, and in Scratch 2.0, it is possible to detect special keys such as shift/ctrl/alt, backspace, enter and tab. None of those work in Scratch 3.0. How does sulfurous handle this?

**Comment by FRALEXAlexander** [comment]
We will try to support the special keys.

We tested many sb2 files on diferent machiens with different browsers and it worked every time so I am sure your browser is the issue.

**Comment by PiotrGrochowski** [comment]
The thing is, Firefox ESR 52.4.1 (32-bit) is a very advanced browser. Even more advanced than Internet Explorer 11 is. So you should debug and see what happened here with Firefox ESR 52.4.1 (32-bit).

**Comment by demesos** [comment]
> 
> 
> "I opened your tetris2019.sb2 with the Scratch 2 offline editor and saved it again."
> 
> This makes the sounds compressed. The original file didn't have compressed sounds. Playtest both the original and the Scratch-saved file in Scratch 2.0 and you might hear the difference in sound, for example in the pause sound (pause is by default assigned to enter).
> 
> **Also, I said any sb2 file has this issue. It doesn't matter, I can't test any sb2 file because all of them have this issue.**

Does the issue that drag and drop does not work also appear when you use the (compressed sounds) file  https://sulfurous.aau.at/~wilfried/tetris2019_2.sb2  ?

**Comment by PiotrGrochowski** [comment]
**Also, I said any sb2 file has this issue. It doesn't matter, I can't test any sb2 file because all of them have this issue.**

Did you not focus on what I said? It was literally bold in the text you quoted.

I tested in Chrome Version 49.0.2623.112 m in my Windows XP virtual machine (I refuse to install Chrome on Windows 10) and I got similar results. When I drag-and-drop a sb2 file, it just gives me back the file in a download. Unlike in Firefox, this happens whether the drag-and-drop is on top of the Scratch url textbox or not.

**So this issue appears in two environments I tested:
Firefox ESR 52.4.1 (32-bit) on Windows 10 (64-bit)
Chrome Version 49.0.2623.112 m on Windows XP (32-bit)**

**Comment by PiotrGrochowski** [comment]
And on Android, this can't be tested at all because Android doesn't seem to support drag-and-drop of files.

**Comment by PiotrGrochowski** [comment]
I don't even have an environment where this feature somehow does work.

**Comment by FRALEXAlexander** [comment]
We are not able to support all old versions of the browsers. The versions you used go back to 2016 thats simply not possible to support

**Comment by PiotrGrochowski** [comment]
Someone should test this on the two browsers I tested this on to attempt to reproduce, and if that succeeds, compare the results to the recent version equivalents of the browsers. Maybe it is a browser compatibility issue; in this case, the feature should really be made more accessible to browsers (including mobile environments where drag-and-drop is impossible).

**Comment by FRALEXAlexander** [comment]
There is no point in testing these old browsers we have not the time or manpower to go through the versions and look for differences if you dont want to install a current version of Firefox or Chrome on your main machine use it in an VM.

**Comment by FRALEXAlexander** [comment]
Did you test only your hacked projects or also some native scratch 2.0 Projects ?

**Comment by PiotrGrochowski** [comment]
As I said, Firefox ESR 52.4.1 (32-bit) is a very advanced browser. Even more advanced than Internet Explorer 11 is. There's no point in designing features that don't work in such advanced browsers.

**Comment by PiotrGrochowski** [comment]
I did test native Scratch 2.0 projects too. This happens with any sb2 file. I don't think sulfurous processes anything, it's the browser itself that gives me the file back.

**Comment by FRALEXAlexander** [comment]
I am not sure if a browser from 2017 can be called "very advanced" in 2019.
Did you try the file that demesos provided ?

**Comment by FRALEXAlexander** [comment]
Can you use drag and drop on other websites ?

**Comment by PiotrGrochowski** [comment]
I installed Chrome on Windows 7 VM. This feature actually worked, but the project itself was very slow — about 1.6 FPS.

**I do not have powerful enough hardware to run the latest browsers.**

**Comment by PiotrGrochowski** [comment]
Yes, drag and drop does work on other websites. But not in sulfurous. 

"I am not sure if a browser from 2017 can be called "very advanced" in 2019."

It really is. Very complex animations such as YouTube videos work fine. The way YouTube works is that a complex stream of bytes is streamed to the browser and it has to decode it into a video using very complicated algorithms. All that, optimized so that even a slow PC can run it. You don't know how much work went into those browsers. For a browser not to be considered advanced you'd have to go back to the days of Internet Explorer 8. Firefox ESR 52.4.1 (32-bit) far exceeds the capabilities of Internet Explorer 9 and deserves to be able to run anything.

**Comment by FRALEXAlexander** [comment]
I dont think we will be able to make sulfurous drag and drop feature work with that wersion of firefox but we are working on an feature to load sb2/sb3 files from external online sources maybe that feature could help you when it is released.
