### ISSUE TITLE
https://scratch.mit.edu/projects/315597243/

### ISSUE THREAD

**Issue by earlymorningtrappin** [Mittagskogel/Sulfurous#195]
https://scratch.mit.edu/projects/315597243/
https://sulfurous.aau.at/#315597243
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

**Comment by FRALEXAlexander** [comment]
This project loads now.
