### ISSUE TITLE
.sb2 files that were dragged and dropped into site, shows blank for packaging and embedding

### ISSUE THREAD

**Issue by BossKaiden** [Mittagskogel/Sulfurous#199]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

**Comment by FRALEXAlexander** [comment]
It is not possible to chache all sb2s that are dragged into sulfurous for embedding oder packaging. If you want to use Sulfurours externaly you can do that with the "Package ZIP" option. You will get a zip file with all files you need just start a webserver and run it.
