### ISSUE TITLE
Learning NPR

### ISSUE THREAD

**Issue by sfederici** [Mittagskogel/Sulfurous#2]
The project looks slower in Sulfurus than in Scratch. I can't neither stop the project nor activate turbo mode.

http://scratch.mit.edu/projects/116997866/
http://mittagskogel.github.io/#116997866
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by Mittagskogel** [comment]
Sorry looks like the link was incorrect. Try: http://newton.nes.aau.at/~sulfurous/

**Comment by sfederici** [comment]
Even when looking the project at http://newton.nes.aau.at/~sulfurous/#116997866 it looks much slower than the original Scratch project (at least on my PC). Maybe the reason is the slower handling of graphical effects? And I can't stop or turbo the project

**Comment by Mittagskogel** [comment]
Weird. It's only the first effect that seems to have this problem. It looks like Sulfurous is ignoring the "run without screen refresh" block. If you use turbo mode it runs faster...
I will look into this.

**Comment by Mittagskogel** [comment]
Wait sorry I missed the part about turbo and stop. That is working fine here, try hard refreshing the page (shift+refresh) maybe your browser cached an older version??? About the graphic effects: The project doesn't use any...

**Comment by sfederici** [comment]
I tried it in Firefox and both turbo and stop work fine. Turbo works fine also in Chrome if I package the project with turbo. But I can't enable/disable turbo in Chrome when the project is not packaged.
