### ISSUE TITLE
とんでるさんかっけぇ(Flying Triangle) Test v0.00c su Scratch

### ISSUE THREAD

**Issue by sfederici** [Mittagskogel/Sulfurous#20]
At least in my PC it looks smoother in Scratch than in Sulfurous. Which is weird :)

http://scratch.mit.edu/projects/142479640/
http://newton.nes.aau.at/~sulfurous/#142479640
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by htmlgames** [comment]
Maybe it's because that project has run without refresh in the custom blocks.
This wasn't coded in originally in the javascript scratch emulator, however I had a go myself on this fork:

https://htmlgames.github.io/htmlgames/differences/UAT/itchy/index.html#142479640 

What do you think?

**Comment by sfederici** [comment]
I can't see much of a difference. Still smoother in Scratch. In Sulfurous/Phosphorous is less fluid.

**Comment by FRALEXGAMING** [comment]
Now it is fluid in Sulfurous. (Verison 0.82)

**Comment by sfederici** [comment]
Confirm, fluid and actually faster too.
