### ISSUE TITLE
Help please!

### ISSUE THREAD

**Issue by mariusmanescu** [Mittagskogel/Sulfurous#203]
I try to convert my scratch project from https://scratch.mit.edu/projects/339928842 to apk, but I fail. Please help to succed. This projects like other is for educational purposes.
https://newton.nes.aau.at/~sulfurous/#339928842

```
Error: HTTP 404: 
    at XMLHttpRequest.xhr.onload (https://sulfurous.aau.at/js/phosphorus.js:469:23)
```

**Comment by FRALEXAlexander** [comment]
The project loads now.
