### ISSUE TITLE
https://scratch.mit.edu/projects/343475480/

### ISSUE THREAD

**Issue by lepythoner** [Mittagskogel/Sulfurous#207]
https://scratch.mit.edu/projects/343475480/
https://sulfurous.aau.at/#343475480
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

this isn't working, giving me an error

**Comment by FRALEXAlexander** [comment]
This Projects work now
