### ISSUE TITLE
New projects

### ISSUE THREAD

**Issue by PeskyPlayz953** [Mittagskogel/Sulfurous#208]
https://scratch.mit.edu/projects/11317273/
https://sulfurous.aau.at/#11317273
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

**Comment by FRALEXAlexander** [comment]
It seems to work fine. If you have a problem please discribe it and reopen the issue
