### ISSUE TITLE
Nothing is showing up

### ISSUE THREAD

**Issue by stxphspace** [Mittagskogel/Sulfurous#209]
The same thing happens with phosphorous, maybe its something on my end?

https://scratch.mit.edu/projects/369283002/
https://sulfurous.aau.at/#369283002
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

**Comment by FRALEXAlexander** [comment]
It is a Scratch 3 project we dont support them yet but we will try do support them soon

**Comment by FRALEXAlexander** [comment]
This project works now
