### ISSUE TITLE
Arrow Keys Android

### ISSUE THREAD

**Issue by TheLuigiFan-XD** [Mittagskogel/Sulfurous#21]
Some Sprites Not Showing Up

http://scratch.mit.edu/projects/146045681/
http://newton.nes.aau.at/~sulfurous/#146045681
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by FRALEXGAMING** [comment]
Project is working just fine on Sulfurous but is not on Scratch. I also tested it on Android.
