### ISSUE TITLE
https://scratch.mit.edu/projects/372430186/

### ISSUE THREAD

**Issue by mazmazen** [Mittagskogel/Sulfurous#211]
This project doesn't work

https://scratch.mit.edu/projects/372430186/
https://sulfurous.aau.at/#372430186
Mozilla/5.0 (Linux; Android 9; ONEPLUS A5000) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.119 Mobile Safari/537.36

**Comment by FRALEXAlexander** [comment]
The project works
