### ISSUE TITLE
https://scratch.mit.edu/projects/380314013/

### ISSUE THREAD

**Issue by Riley1912** [Mittagskogel/Sulfurous#215]
It won't load my game that I wanted to play. why?

https://scratch.mit.edu/projects/380314013/
https://sulfurous.aau.at/#380314013
Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.106 Safari/537.36

**Comment by FRALEXAlexander** [comment]
It's a problem with Scratch 3

**Comment by FRALEXAlexander** [comment]
It no longer available on scratch I can not test your project.
