### ISSUE TITLE
http://scratch.mit.edu/projects/148149526/

### ISSUE THREAD

**Issue by sfederici** [Mittagskogel/Sulfurous#22]
Much darker in Sulfurous.

http://scratch.mit.edu/projects/148149526/
http://newton.nes.aau.at/~sulfurous/#148149526
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by FRALEXGAMING** [comment]
The Result from this project is the same in Sulfurous and Scratch now.

**Comment by sfederici** [comment]
Confirm
