### ISSUE TITLE
THIS IS A BAD ERROR!!!

### ISSUE THREAD

**Issue by githubmaster1235** [Mittagskogel/Sulfurous#227]
https://scratch.mit.edu/projects/376978226
https://newton.nes.aau.at/~sulfurous/#376978226

```
Error: HTTP 404: 
    at XMLHttpRequest.xhr.onload (https://sulfurous.aau.at/js/phosphorus.js:469:23)
```

**Comment by FRALEXAlexander** [comment]
the project loads now but I cant check the expected behavior because the project is no longer on scratch.
