### ISSUE TITLE
https://scratch.mit.edu/projects/278296619/

### ISSUE THREAD

**Issue by gatzke** [Mittagskogel/Sulfurous#233]
Project won't load in sulfurous and I have no clue why.  Sounds maybe?

https://scratch.mit.edu/projects/278296619/
https://sulfurous.aau.at/#278296619
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

**Comment by FRALEXAlexander** [comment]
Some SB3 projects now work with Sulfurous yours is one of them.
