### ISSUE TITLE
https://scratch.mit.edu/projects/400312180/

### ISSUE THREAD

**Issue by timjbuch** [Mittagskogel/Sulfurous#237]
https://scratch.mit.edu/projects/400312180/
https://sulfurous.aau.at/#400312180
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36

**Comment by FRALEXAlexander** [comment]
This project now works.
