### ISSUE TITLE
https://scratch.mit.edu/projects/400185398/

### ISSUE THREAD

**Issue by PetitScratchCat** [Mittagskogel/Sulfurous#238]
`<script src='https://sulfurous.aau.at/js/embed.js?id=400185398&resolution-x=480&resolution-y=360&auto-start=true&light-content=false'></script>`

https://scratch.mit.edu/projects/400185398/
https://sulfurous.aau.at/#400185398
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0

**Comment by FRALEXAlexander** [comment]
The project now works
