### ISSUE TITLE
http://scratch.mit.edu/projects/152330405/

### ISSUE THREAD

**Issue by sfederici** [Mittagskogel/Sulfurous#24]
NOTE: to see the result you have to wait a little while. But the final result is wrong (a lot of white dots instead of the correct ones).

http://scratch.mit.edu/projects/152330405/
http://newton.nes.aau.at/~sulfurous/#152330405
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.1144

**Comment by FRALEXGAMING** [comment]
The project is not on Scratch anymore but I think the result in Sulfurous is the right one. I see a Koala. Just reopen the issue if i am wrong.

**Comment by sfederici** [comment]
(sorry, I shared the project now) I can see only the initial dots and then, after a while, the final moving dots, but I don't see the middle process that divides the page again and again so to scan it.
