### ISSUE TITLE
Last digit of project id is cut off

### ISSUE THREAD

**Issue by drherobrine** [Mittagskogel/Sulfurous#241]
On sulfurous.aau.at, I typed the project id as '408590708'. However, my project could not be loaded as the id kept getting cut down to '40859070', removing the '8' at the end.

https://scratch.mit.edu/projects/40859070/
https://sulfurous.aau.at/#40859070
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0

**Comment by 2br-2b** [comment]
That is odd - the project works for me. I'm using `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0`.

**Comment by FRALEXAlexander** [comment]
It seems to work fine in Chrome too. please reopen the issue if it is still not loading please send me the output of your browser console.
