### ISSUE TITLE
Shift key not regognized

### ISSUE THREAD

**Issue by Isvvc** [Mittagskogel/Sulfurous#26]
The <key <> pressed?> Boolean does not normally support the shift key, but there are ways of forcing it in so that shift key presses can be recognized by the Flash scratch player, but they are not recognized by the Sulfurous player.

http://scratch.mit.edu/projects/25713359/
http://newton.nes.aau.at/~sulfurous/#25713359
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by htmlgames** [comment]
I hacked the keypress stuff for something similar (as some games use it as an action key):

As a start, you add the key code here:
  var KEY_CODES = {
    'ctrl': 17,
    'space': 32,
    'left arrow': 37,
    'up arrow': 38,
    'right arrow': 39,
    'down arrow': 40
  };

however it gets messy quickly implementing the hacked keypress block (griffpatch)
some examples on my fork:

ctrl key hack:
https://htmlgames.github.io/htmlgames/differences/UAT/itchy/index.html#55416430
https://htmlgames.github.io/htmlgames/differences/UAT/itchy/index.html#56667792

hacked keypress block:
https://htmlgames.github.io/htmlgames/differences/UAT/itchy/index.html#19204741

**Comment by FRALEXGAMING** [comment]
The project http://scratch.mit.edu/projects/25713359/ is not existing on the Scratch server anymore but the shift key is regognized in Sulfurous. (tested in version 0.81)

**Comment by htmlgames** [comment]
Hi, I know this issue is closed now, but I have recently finished updating all the keypress stuff yesterday (so it works with hacked ascii blocks as well) - you may want to update your branch if your interested...

**Comment by FRALEXGAMING** [comment]
Yes sure if it works better than our current sollution. Send me the file

**Comment by htmlgames** [comment]
https://github.com/htmlgames/htmlgames.github.io/blob/master/htmlgames/differences/UAT/itchy/phosphorus.js

**Comment by FRALEXGAMING** [comment]
Your code is now in the phosphorus.js thanks for your help.
