### ISSUE TITLE
Color Effect, Music Quality, and Pen Shade

### ISSUE THREAD

**Issue by Something-Went-Terribly-Wrong** [Mittagskogel/Sulfurous#27]
When will the color effect be implemented into Sulfurous?
Here is a small example of how a project is affected:
https://scratch.mit.edu/projects/155769553
http://newton.nes.aau.at/~sulfurous/app.html?id=155769553&turbo=false&full-screen=true&resolution-x=
Left and right arrows change color, but the circular cursor and the triangle minions only change color in the scratch player.

Also, for some reason, the music quality drops 
and the darkest color of the pen shade is black when it should be a dark green.

**Comment by FRALEXGAMING** [comment]
The color effect is now working but it needs some tweaks to be accurate.

**Comment by FRALEXGAMING** [comment]
The projekt is now working on sulfurous Version 0.85
