### ISSUE TITLE
Texture mapped 3D cube su Scratch

### ISSUE THREAD

**Issue by sfederici** [Mittagskogel/Sulfurous#28]
For pixel size 1 and cube size 9, Scratch is slightly faster.

http://scratch.mit.edu/projects/157160342/
http://newton.nes.aau.at/~sulfurous/#157160342
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.1144

**Comment by htmlgames** [comment]
Same on this branch with Run With Screen Refresh implimented:

https://htmlgames.github.io/htmlgames/differences/UAT/itchy/index.html#157160342

**Comment by sfederici** [comment]
In my PC https://htmlgames.github.io/htmlgames/differences/UAT/itchy/index.html#157160342 pen size 2 and cube size 6 seems slightly faster. But I can't drag the sliders to check it.

**Comment by FRALEXGAMING** [comment]
Scratch is solwer than Sulfourus in this situation. (version 0.83)c
