### ISSUE TITLE
TETRIS online in Scratch su Scratch

### ISSUE THREAD

**Issue by sfederici** [Mittagskogel/Sulfurous#29]
When blocks fall down they are one color only (red).

http://scratch.mit.edu/projects/64706676/
http://newton.nes.aau.at/~sulfurous/#64706676
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.1144

**Comment by htmlgames** [comment]
Colour Effect may need coding?

**Comment by FRALEXGAMING** [comment]
I cant check this error couse the Project does not work on Scratch
