### ISSUE TITLE
Longest Stroke NPR Guy

### ISSUE THREAD

**Issue by sfederici** [Mittagskogel/Sulfurous#3]
It doesn't work on my PC (only monitors show up on the Stage) neither in normal mode nor in turbo mode.

http://scratch.mit.edu/projects/117734375/
http://mittagskogel.github.io/#117734375
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by Mittagskogel** [comment]
Looks like you're using the wrong link for Sulfurous, please try
http://newton.nes.aau.at/~sulfurous/#117734375
instead. I'll take down the other version and leave a notice there.

**Comment by Mittagskogel** [comment]
I noticed that the wrong link may have been generated by the bug-reporter.
Which link did you actually use?

**Comment by sfederici** [comment]
Exactly the one you said, http://newton.nes.aau.at/~sulfurous/#117734375

**Comment by Mittagskogel** [comment]
What do you mean by "monitors"? Are you aware that you need to press [space] to start the project?

**Comment by sfederici** [comment]
You're perfectly right. I had to postpone the test on Sulfurous and then when I was back I forgot about the space. Sorry for this alert. Thanks for reminding me.
