### ISSUE TITLE
TANK DEFENSE!

### ISSUE THREAD

**Issue by IryRasmo** [Mittagskogel/Sulfurous#31]
This project doesn't load properly, and the sounds are lower quality

http://scratch.mit.edu/projects/138090989/
http://newton.nes.aau.at/~sulfurous/#138090989
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30

**Comment by FRALEXGAMING** [comment]
I think the sound quality is now good just reopen the Issue.
