### ISSUE TITLE
Circular Motion vs Harmonic Motion with Speed

### ISSUE THREAD

**Issue by sfederici** [Mittagskogel/Sulfurous#32]
It doesn't show the text of the "explanation" sprite

https://scratch.mit.edu/projects/70959740/
https://newton.nes.aau.at/~sulfurous/#70959740
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 OPR/45.0.2552.881

**Comment by htmlgames** [comment]
You need to update the svg code in your branch for it to work.
example of it working: (using chrome)

https://htmlgames.github.io/htmlgames/differences/UAT/itchy/index.html#70959740

**Comment by sfederici** [comment]
Thanks! Why aren't you updating the code on sulfurous too? :)

**Comment by htmlgames** [comment]
Hi, my SVG code isn't working on some other projects. eg 132035951, but yours is. Others on yours fail (like above) but my fork works. My code is not therefore ready for a pull request for this branch.

**Comment by FRALEXGAMING** [comment]
htmlgames is your svg code now ready for an pull request ?

**Comment by htmlgames** [comment]
I've taken a look and I'm still using canvg.js, this is completely different to how you (now) do it. Could be tricky! Note I only got it to work in Chrome and Firefox

For a start - Make sure you include all the scratch font's in your branch.

**Comment by FRALEXGAMING** [comment]
Do you use hangouts ? or a other Messanger ? I would like to write with you some were else.

**Comment by htmlgames** [comment]
https://htmlgames.github.io/

click the Social link in the top left :)

**Comment by Mittagskogel** [comment]
I believe I have fixed the issue in sulfurous. Please tell me if it's working for you.

**Comment by sfederici** [comment]
Now it works. Thanks.
