### ISSUE TITLE
Gradient Errors

### ISSUE THREAD

**Issue by Alzter** [Mittagskogel/Sulfurous#34]
Linear Gradients do not render in the right direction,
Radial Gradients do not render at all,
And outlines with Gradients also don't render.

**Comment by htmlgames** [comment]
Ok. Please supply a simple project demostrating this issue as it helps fixing code :)

**Comment by Alzter** [comment]
OK. Here: https://sulfurous.aau.at/~sulfurous/#167127961

**Comment by htmlgames** [comment]
like this?
https://htmlgames.github.io/htmlgames/differences/UAT/itchy/index.html#167127961

**Comment by Alzter** [comment]
That works! Could you fix sulfurous to do the same?

**Comment by htmlgames** [comment]
It's in the pipeline :)

I have to merge quite a lot of (svg related) code with the way it's currently done on this branch - and I don't want to fix one project only to break another...

**Comment by Alzter** [comment]
Aw. Ok.

**Comment by Mittagskogel** [comment]
I believe it is now fixed. Does this also fix https://github.com/Mittagskogel/Sulfurous/issues/25?

**Comment by FRALEXAlexander** [comment]
Vectors, and gradients are fixed now in sulfurous
