### ISSUE TITLE
Ladybug Indy 500 auf Scratch

### ISSUE THREAD

**Issue by demesos** [Mittagskogel/Sulfurous#36]
The jump sound does not play in Sulfurous. It works in Scratch and Phosphorus.

https://scratch.mit.edu/projects/166436932/
https://sulfurous.aau.at/#166436932
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0

**Comment by FRALEXGAMING** [comment]
Jump sound is playing in Sulfurous Version 0.82

**Comment by Mittagskogel** [comment]
Fixed.
