### ISSUE TITLE
Crossy Duck su Scratch

### ISSUE THREAD

**Issue by sfederici** [Mittagskogel/Sulfurous#38]
The duck doesn't detect the contact with the upper line so that it doesn't bounce back.

https://scratch.mit.edu/projects/168512204/
https://sulfurous.aau.at/#168512204
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32

**Comment by htmlgames** [comment]
in here, line 3655:


} else if (block[0] === 'wait:elapsed:from:') {
--
  | if(block[1] != 0){
  | wait(num(block[1]));
  | }


get rid of the if wrapper so just the wait(num(block[1])); is left
This will fix the issue.

**Comment by FRALEXGAMING** [comment]
You are right htmlgames this has fixed the Issue thanks for your help i will put a link to your git profile in the js 👍
