### ISSUE TITLE
3D Faroes Eclipse Experience auf Scratch

### ISSUE THREAD

**Issue by demesos** [Mittagskogel/Sulfurous#39]
The earth in the intro ("Where are the faroer islands") is not shown.
Some buttons are not displayed.
The rendered graphics look different and the sun is not displayed.

https://scratch.mit.edu/projects/25071751/
https://sulfurous.aau.at/#25071751
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0

**Comment by Mittagskogel** [comment]
Fixed.
