### ISSUE TITLE
Aurora's Quest auf Scratch

### ISSUE THREAD

**Issue by demesos** [Mittagskogel/Sulfurous#40]
Sound is not playing when starting the project in Firefox.
I was using Sulfurous 0.84

https://scratch.mit.edu/projects/139825436/
https://sulfurous.aau.at/#139825436
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0

**Comment by FRALEXGAMING** [comment]
The Princess is not showing on the stage in Firefox.

**Comment by Mittagskogel** [comment]
Fixed.
