### ISSUE TITLE
Touchscreen bug

### ISSUE THREAD

**Issue by Alzter** [Mittagskogel/Sulfurous#43]
The flag buttons do not work when you click them if you have a touchscreen PC, but they do work when tapped. Can you make them work on click?

**Comment by Mittagskogel** [comment]
It should be working now, but I can't test it because I don't have a hybrid PC. Does it work correctly now?

**Comment by demesos** [comment]
I tested it with a touchscreen windows PC  under Chrome and Firefox, it works well with mouse click and with tapping.
