### ISSUE TITLE
Where To Get Free Resources auf Scratch

### ISSUE THREAD

**Issue by demesos** [Mittagskogel/Sulfurous#48]
Project does not load neither on Firfox nor on Chrome.

https://scratch.mit.edu/projects/103283381/
https://sulfurous.aau.at/#103283381
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by htmlgames** [comment]
I can get it to load but the books aren't rendering the text when opened (pics ok)

**Comment by Mittagskogel** [comment]
I've fixed the issue for non-ascii characters in text, so project is loading normally now... But I also see the problem with the missing text.

**Comment by Mittagskogel** [comment]
It looks like scratch sometimes forgets to set the color of text in svgs, leaving it set to 'none'. If the tag is set to 'none', I change it to #7F7F7F. I'm not sure if this is correct behavior...
