### ISSUE TITLE
Winter Olympics Slalom

### ISSUE THREAD

**Issue by demesos** [Mittagskogel/Sulfurous#5]
The letters in the final banner at the finish are placed too high (the finish banner is a vector graphic with a text box in it). It's a minor thing though.

http://scratch.mit.edu/projects/18039363/
http://mittagskogel.github.io/#18039363
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by Mittagskogel** [comment]
Fixed.
