### ISSUE TITLE
Project 16063324 not loading blank svg's

### ISSUE THREAD

**Issue by htmlgames** [Mittagskogel/Sulfurous#50]
Hi,
 I noticed this project wasn't loading due to it having blank svg's EDIT: (with blank images?). The way I work-around this issue is to load a hard-coded 1 pixel transparent png. Not the best way but gets the game loaded.

https://sulfurous.aau.at/~sulfurous/#16063324

example of fix:

https://htmlgames.github.io/htmlgames/differences/UAT/itchy/index.html#16063324

https://github.com/htmlgames/htmlgames.github.io/blob/master/htmlgames/differences/UAT/itchy/phosphorus.js#L275

**Comment by FRALEXAlexander** [comment]
The Project loads now also in Sulfurous.
