### ISSUE TITLE
Random Art Generator v1.1 在 Scratch 上

### ISSUE THREAD

**Issue by cyx2015s** [Mittagskogel/Sulfurous#59]
https://scratch.mit.edu/projects/174907717
https://newton.nes.aau.at/~sulfurous/#174907717

```
Error: XHR Error
    at XMLHttpRequest.xhr.onerror (https://sulfurous.aau.at/js/phosphorus.js:445:21)
```

**Comment by htmlgames** [comment]
It loads in Chrome Windows 10
(I used https://sulfurous.aau.at/#174907717 as well)
However it doesn't complete?

**Comment by FRALEXAlexander** [comment]
I don´t see any error so I will close and declare this as fixed
