### ISSUE TITLE
Feed Me! [Nasi Goreng Edition]

### ISSUE THREAD

**Issue by demesos** [Mittagskogel/Sulfurous#6]
1. The second sprite ("smile") is shown all yellow instead of intented colors.
2. The second line of the vector text ("HIGHSCORE") is not shown.

http://scratch.mit.edu/projects/114659194/
http://mittagskogel.github.io/#114659194
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0

**Comment by FRALEXGAMING** [comment]
Now all is showing up correct.
