### ISSUE TITLE
Chess in 3D v0.1 su Scratch

### ISSUE THREAD

**Issue by sfederici** [Mittagskogel/Sulfurous#64]
Stuck at splash screen

https://scratch.mit.edu/projects/178663717/
https://sulfurous.aau.at/#178663717
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by DarDoro** [comment]
There a are few problems:
1) critical : sprite "Controller", script "then backdrop switch to Thumb" contains "stop all scripts". This code is probably activated by script problem - switching to non existent backdrop "Main" during startup.
2) phosphorus.js : lack of "showList()", "hideList()" method, issue #58 
3) project itself has syntax errors in "project.json". Call of custom block "comment" is wrongly encoded.

**Comment by FRALEXAlexander** [comment]
The issue will be fixed in verison 0.87 of sulfourus.
