### ISSUE TITLE
Mandelbrot Set Explorer 3.3D su Scratch

### ISSUE THREAD

**Issue by sfederici** [Mittagskogel/Sulfurous#69]
Buttons shown in wrong position. Buttons not working.

https://scratch.mit.edu/projects/181341231/
https://sulfurous.aau.at/#181341231
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

**Comment by FRALEXAlexander** [comment]
The projects behaviour is simmilar to scratch the only difference I noticed was the much better performance in sulfourus.
