### ISSUE TITLE
Snow [100% PEN]

### ISSUE THREAD

**Issue by sfederici** [Mittagskogel/Sulfurous#7]
The snow doesn't fall down.

http://scratch.mit.edu/projects/120677796/
http://mittagskogel.github.io/#120677796
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

**Comment by sfederici** [comment]
Thanks. This means that I could add "source += 'S.forward(0);\n'" in the translation of "putPenDown" and that should work, right?

**Comment by DarDoro** [comment]
Remix 
http://sulfurous.aau.at/#154463389
BTW: pen is not needed at all. Sprite with white dot or cross or various snowflake images give better results. You can consider "parallax" scrolling (small objects fall slower) to get pseudo 3D.

**Comment by sfederici** [comment]
Thanks. I had already made a remix myself adding "move 0" and it worked fine. The project is not mine. I was just interested in why it didn't work in Sulfurous. Do you think my proposal (adding S.forward) will make this (and similar projects) work?

**Comment by DarDoro** [comment]
I looked at sources only briefly, but think that Sprite.prototype.dotPen@phosphorus.js needs some workaround for small pen. Maybe changing from arc to rectangle for small pens. "source += 'S.forward(0);\n'" makes twice as much canvas operations and may slow down pen projects.

**Comment by DarDoro** [comment]
I've tested with latest version from github repo on my local server. It works as expected. Unfortunately official site http://sulfurous.aau.at/ is serving outdated version, with pen radius calculated as `Math.floor(this.penSize / 2)`.

**Comment by FRALEXGAMING** [comment]
With version 0.83 of Sulfurous (release today afternoon) will the project work in the same way as on Scratch.
