### ISSUE TITLE
N-body gravitation sur Scratch

### ISSUE THREAD

**Issue by Ascor8522** [Mittagskogel/Sulfurous#70]
Particles on this project
https://scratch.mit.edu/projects/183744743/
let white/grey marks on the screen.
It doesn't in the original project with the Scratch player.
 
https://sulfurous.aau.at/#183744743
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by RedMAngo22** [comment]
://

**Comment by htmlgames** [comment]
looks like the trail colour is created from the sprite1 costume against the stage background (try messing with the colour to see what I mean)

I'm guessing it's some sort of colour conversion being incorrect...
