### ISSUE TITLE
Pulsing 3D wires su Scratch

### ISSUE THREAD

**Issue by sfederici** [Mittagskogel/Sulfurous#78]
It works well in phosphorous, but here in sulfurous the top and bottom parts of the stage do not refresh correctly.

https://scratch.mit.edu/projects/195930792/
https://sulfurous.aau.at/#195930792
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

**Comment by RexSoulguardian** [comment]
What do you mean by not refresh correctly?

**Comment by sfederici** [comment]
I hope I will be able to answer your question soon, as soon as sulfurous will allow me to load the project (I don't remember the project exactly right now and now when I load the project I only get a red project address bar.)

**Comment by FRALEXAlexander** [comment]
I can start your project  with this link https://sulfurous.aau.at/#195930792 and it loads.

**Comment by sfederici** [comment]
Yes, not it loads and it works as expected. Thanks.
