### ISSUE TITLE
Click To Be Cool

### ISSUE THREAD

**Issue by BleachDrinker** [Mittagskogel/Sulfurous#79]
I know that this a web site that is made to make laggy scratch games less laggy. From there I know you don't have access to the scratch servers. I know this because I made this game and I know what values are cloud and not and that is when the problem comes in. Here is my thought. Maybe you can team up with scratch to make this website work under scratch. I know that seems a bit weird but it will overall help you as a buisness possibly and make the website better!

https://scratch.mit.edu/projects/196944704/
https://sulfurous.aau.at/#196944704
Mozilla/5.0 (X11; CrOS x86_64 10032.75.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.116 Safari/537.36

**Comment by NIXE-Hub** [comment]
It would be cool, but due to the fact that Sulfurous is hosted on GitHub, then everyone would have access to the scratch server APIs, causing cloud variables to be hacked on peoples' games etc.!

**Comment by FRALEXAlexander** [comment]
Sulfurous will not be able to use Scratch Cloud variables but we will add a feature for Sulfurous only Cloud Variables.

**Comment by NIXE-Hub** [comment]
That would be great!

**Comment by FRALEXAlexander** [comment]
We implementet cloud variables it is now possible to use scratch cloud variables but the data will not work across sulfurous and scratch. You can also use variables with the name sulf.c.*** the values of that variables will also be stored in the cloud

**Comment by NIXE-Hub** [comment]
That's cool! That's a great feature.
