### ISSUE TITLE
Portal 3D: Test Chamber 13 (Scratch edition)

### ISSUE THREAD

**Issue by demesos** [Mittagskogel/Sulfurous#8]
The sounds, especially GLaDOS' speech when entering the room, are of much worse quality than in the scratch version. Dunno if there is an easy fix to it though.

http://scratch.mit.edu/projects/124823106/
http://mittagskogel.github.io/#124823106
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0

**Comment by Mittagskogel** [comment]
I believe it is fixed now.

**Comment by demesos** [comment]
Tested with Firefox and Chrome, works well.
