### ISSUE TITLE
Lists not showing.

### ISSUE THREAD

**Issue by Killernotch101** [Mittagskogel/Sulfurous#83]
As many of you can easily see for yourself, lists do NOT show up. Now, this is a pain in the butt for those of us who use Sulfurous a LOT for math programs. (It’s excellent! Sulfurous, I mean.) Is this a bug, or just not a feature yet?

**Comment by htmlgames** [comment]
The logic is being worked on.

**Comment by FRALEXAlexander** [comment]
Lists will work in version 0.94
