### ISSUE TITLE
Primes Lister

### ISSUE THREAD

**Issue by FintasticMan** [Mittagskogel/Sulfurous#84]
I can't use this project i just made, I think it is because lists don't work in your player.  I would be very grateful if you could fix it.

https://scratch.mit.edu/projects/167841647/
https://sulfurous.aau.at/#167841647
Mozilla/5.0 (X11; CrOS x86_64 10032.86.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.140 Safari/537.36

**Comment by htmlgames** [comment]
I'm trying to implement lists on this fork first (it's quite tricky):

https://htmlgames.github.io/htmlgames/differences/UAT/itchy/index.html#167841647

I then can patch to Sulfurous, however they use different zooming styles that I have to work out (once the general list logic is done)

**Comment by FintasticMan** [comment]
I saw that but what is lacking is Turbo Mode

**Comment by FintasticMan** [comment]
I'm trying to make a website just for a test an Sulphorous seems great but either it's missing Turbo Mode or lists
Don't get me wrong, I really love what you guys are doing, but these things are just the icing on the cake.

**Comment by htmlgames** [comment]
Hold down shift and click the flag for the fork above = turbo mode

**Comment by htmlgames** [comment]
It may also work on Sulphurous.( I'm on my phone so cannot test)

**Comment by htmlgames** [comment]
Hey FintasticMan , I've implemented a turbo mode on the list on the fork - if it's running in turbo mode the list(s) only redraw every second. This is now kicking out ~320 primes a second (compared to turbo mode scratch ~110 per second ).

What do you think of this as a possible turbo mode solution?

**Comment by FintasticMan** [comment]
I am sorry I haven't commented for a while, but I think that is a fine solution. 😄

**Comment by FRALEXAlexander** [comment]
Lists will work in version 0.94
