### ISSUE TITLE
https://scratch.mit.edu/projects/203279651/  There is only once when it worked

### ISSUE THREAD

**Issue by SweetieMusic** [Mittagskogel/Sulfurous#87]
https://scratch.mit.edu/projects/203279651/
https://sulfurous.aau.at/#203279651
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

**Comment by FRALEXAlexander** [comment]
It works every time i tested it
