### ISSUE TITLE
https redirect issue - how to fix

### ISSUE THREAD

**Issue by htmlgames** [Mittagskogel/Sulfurous#9]
Hi Mittagskogel,
 Looks like you have moved to https. Can I suggest that you update index.html so that these lines

  if (location.protocol === 'https:') {
    //location.replace(('' + location).replace(/^https:/, 'http:')); // pf: we run on https now
  }

be either removed (or comment out as I have). It will stop the redirect issue (You need to do this for all instances btw).

Cheers!

P.S. just realized this effects your github only page: https://mittagskogel.github.io/
(Didn't see the other http link which works correctly).

P.P.S are you still actively updating this project? good to see you made a start on tackling the effects code.

**Comment by Mittagskogel** [comment]
I'm hoping to update a few things soon,
thanks for your interest in this project :)
