### ISSUE TITLE
https://scratch.mit.edu/projects/21276116/

### ISSUE THREAD

**Issue by LapisLake36** [Mittagskogel/Sulfurous#93]
https://scratch.mit.edu/projects/21276116/
https://sulfurous.aau.at/#21276116
Mozilla/5.0 (X11; CrOS x86_64 10032.86.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.140 Safari/537.36

**Comment by LapisLake36** [comment]
It isn't loading at all.

**Comment by htmlgames** [comment]
On your ground sprite you have an emtpy 0x0 image (id 4) this is what is stopping the project from loading.

**Comment by FRALEXAlexander** [comment]
I added htmlgames version of the fix to sulfurous v0.88 to make the project run.
