### ISSUE TITLE
Dream- A escape platform game v2.8 [NEW UPDATE

### ISSUE THREAD

**Issue by MegaPekka2000** [Mittagskogel/Sulfurous#97]
https://scratch.mit.edu/projects/203492268/
https://sulfurous.aau.at/#203492268
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
The colors changed suddenly

**Comment by htmlgames** [comment]
Your interesting coding style reminds me of this issue (wont fix):

https://github.com/htmlgames/htmlgames.github.io/issues/19
